table _Measures
	lineageTag: a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6
	isHidden

	/// Procurement Measures
	measure 'Total Spend EUR' = SUM(fact_procurement[spend_eur])
		formatString: #,##0
		displayFolder: Procurement

	measure 'YoY Spend Growth %' =
		VAR CurrentPeriod = [Total Spend EUR]
		VAR PriorPeriod = CALCULATE([Total Spend EUR], SAMEPERIODLASTYEAR(gold_dim_date[date]))
		RETURN
		    DIVIDE(CurrentPeriod - PriorPeriod, PriorPeriod, 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Procurement

	/// Sustainability Measures
	measure 'Avg EPI Score' =
		CALCULATE(
		    AVERAGE(fact_epi_score[score]),
		    gold_dim_indicator[source_system] = "EPI"
		)
		formatString: 0.0
		displayFolder: Sustainability

	measure 'Spend-Weighted EPI Score' =
		SUMX(
		    SUMMARIZE(
		        fact_procurement,
		        fact_procurement[supplier_hq_country_key]
		    ),
		    VAR CountrySpend = CALCULATE([Total Spend EUR])
		    VAR CountryEPI =
		        CALCULATE(
		            [Avg EPI Score],
		            FILTER(
		                fact_epi_score,
		                fact_epi_score[country_key] = fact_procurement[supplier_hq_country_key]
		            )
		        )
		    RETURN
		        CountrySpend * CountryEPI
		) / [Total Spend EUR]
		formatString: 0.0
		displayFolder: Sustainability

	measure '% Spend - High EPI (>60)' =
		VAR HighEPISpend =
		    CALCULATE(
		        [Total Spend EUR],
		        FILTER(
		            fact_epi_score,
		            fact_epi_score[score] >= 60 &&
		            RELATED(gold_dim_indicator[source_system]) = "EPI"
		        )
		    )
		RETURN
		    DIVIDE(HighEPISpend, [Total Spend EUR], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sustainability

	/// Risk Measures
	measure 'Max Supply Concentration %' =
		VAR MaxShare = MAXX(fact_supply_share, VALUE(fact_supply_share[share_pct]))
		RETURN
		    DIVIDE(MaxShare, 100, 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Risk

	measure 'HHI Index' =
		SUMX(
		    fact_supply_share,
		    POWER(DIVIDE(VALUE(fact_supply_share[share_pct]), 100, 0), 2)
		)
		formatString: 0.000
		displayFolder: Risk

	measure 'High Risk Material Count' =
		CALCULATE(
		    DISTINCTCOUNT(fact_supply_share[material_key]),
		    VALUE(fact_supply_share[share_pct]) > 50
		)
		formatString: #,##0
		displayFolder: Risk

	measure 'Diversification Score' =
		VAR HHI = [HHI Index]
		RETURN
		    1 - HHI
		formatString: 0.000
		displayFolder: Risk

	measure 'Top 3 Countries Spend %' =
		VAR Top3Spend =
		    CALCULATE(
		        [Total Spend EUR],
		        TOPN(
		            3,
		            ALLSELECTED(gold_dim_country),
		            [Total Spend EUR],
		            DESC
		        )
		    )
		RETURN
		    DIVIDE(Top3Spend, CALCULATE([Total Spend EUR], ALLSELECTED(gold_dim_country)), 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Risk

	measure 'Spend Exposure at Risk' =
		SUMX(
		    SUMMARIZE(
		        fact_procurement,
		        fact_procurement[supplier_hq_country_key],
		        fact_procurement[material_key]
		    ),
		    VAR MaterialSpend = CALCULATE([Total Spend EUR])
		    VAR SupplyConcentration =
		        CALCULATE(
		            MAXX(fact_supply_share, VALUE(fact_supply_share[share_pct]))
		        ) / 100
		    VAR EpiScore = CALCULATE([Avg EPI Score])
		    VAR RiskFactor = SupplyConcentration * (1 - DIVIDE(EpiScore, 100, 0))
		    RETURN
		        MaterialSpend * RiskFactor
		)
		formatString: #,##0
		displayFolder: Risk

	measure 'Material Risk Index' =
		VAR LatestSupplyYear = MAXX(fact_supply_share, fact_supply_share[year])
		VAR LatestEPIYear = MAXX(fact_epi_score, fact_epi_score[year])
		RETURN
		    SUMX(
		        SUMMARIZE(
		            fact_supply_share,
		            fact_supply_share[material_key],
		            fact_supply_share[country_key]
		        ),
		        VAR SupplyShare =
		            CALCULATE(
		                VALUE(fact_supply_share[share_pct]) / 100,
		                fact_supply_share[year] = LatestSupplyYear
		            )
		        VAR EPIScore =
		            CALCULATE(
		                [Avg EPI Score],
		                fact_epi_score[year] = LatestEPIYear
		            )
		        VAR RiskScore = SupplyShare * (1 - DIVIDE(EPIScore, 100, 0))
		        RETURN
		            RiskScore
		    )
		formatString: 0.000
		displayFolder: Risk

	/// Operational Measures
	measure 'Total Quantity' = SUM(fact_procurement[quantity_base])
		formatString: #,##0
		displayFolder: Procurement

	measure 'Transaction Count' = COUNTROWS(fact_procurement)
		formatString: #,##0
		displayFolder: Procurement

	measure 'Supplier Countries Count' = DISTINCTCOUNT(fact_procurement[supplier_hq_country_key])
		formatString: #,##0
		displayFolder: Procurement

	measure 'Materials Count' = DISTINCTCOUNT(fact_procurement[material_key])
		formatString: #,##0
		displayFolder: Procurement

	measure 'Avg Spend per Transaction' =
		DIVIDE([Total Spend EUR], [Transaction Count], 0)
		formatString: #,##0
		displayFolder: Procurement

	/// Time Intelligence Measures
	measure 'Latest EPI Score' =
		VAR LatestYear = MAXX(fact_epi_score, fact_epi_score[year])
		RETURN
		    CALCULATE(
		        AVERAGE(fact_epi_score[score]),
		        fact_epi_score[year] = LatestYear,
		        gold_dim_indicator[source_system] = "EPI"
		    )
		formatString: 0.0
		displayFolder: Sustainability

	partition _Measures = calculated
		mode: import
		source = ROW("Measure Placeholder", 1)

	annotation PBI_ResultType = Table

