table Indicator_Years
	lineageTag: bb3ddce2-8fa2-4545-945b-753c8407f2fc

	measure 'Supply Share Latest' =
			
			VAR LatestYear = [Debug - Latest Supply Year]
			RETURN
			CALCULATE(
			    DIVIDE(AVERAGEX(fact_supply_share, VALUE(fact_supply_share[share_pct])), 100),
			    fact_supply_share[year] = LatestYear
			)
		lineageTag: 2ee0871e-097b-437c-a318-a71c8e245cfd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		formatString: 0
		lineageTag: 2fd554ba-68c4-4b2e-8405-62dfa466fce1
		summarizeBy: none
		isNameInferred
		sourceColumn: [Year]

		annotation SummarizationSetBy = Automatic

	column YearLabel
		lineageTag: c68587d4-1b5f-45b2-99ac-3305963e670d
		summarizeBy: none
		isNameInferred
		sourceColumn: [YearLabel]

		annotation SummarizationSetBy = Automatic

	partition Indicator_Years = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Year", INTEGER,
				    "YearLabel", STRING,
				    {
				        {2019, "2019"},
				        {2020, "2020"},
				        {2021, "2021"},
				        {2022, "2022"},
				        {2023, "2023"},
				        {2024, "2024"}
				    }
				)

	annotation PBI_Id = a834deb17e20473ca3babf9f66cb5298

